export const FIRMS = {
  'apex-edge': {
    id: 'apex-edge',
    name: 'Apex Edge Capital',
    domain: 'apexedge.example',
    initials: 'AE',
    category: 'Futures + Forex prop firm',
    founded: 2021,
    hq: 'Austin, Texas',
    rating: 4.8,
    reviews: 1283,
    trustScore: 92,
    tagline: 'Two-step evaluation with instant funding on pass and a flat 90% split — the volume leader for futures traders in 2026.',
    oneLine: 'Best for high-volume futures day-traders who want fast payouts and a transparent rulebook.',
    url: 'https://apexedge.example',
    highlights: [
      { label: 'Max funding', value: '$400,000', accent: true },
      { label: 'Profit split', value: '90 / 10' },
      { label: 'Eval fee from', value: '$97' },
      { label: 'Payout window', value: '24 hours' },
      { label: 'Founded', value: '2021' },
      { label: 'HQ', value: 'Austin, TX' },
    ],
    scoreBreakdown: [
      { label: 'Capital terms', value: 4.9 },
      { label: 'Trader rules', value: 4.6 },
      { label: 'Payout reliability', value: 4.9 },
      { label: 'Operational maturity', value: 4.5 },
      { label: 'Cost to start', value: 4.8 },
      { label: 'Trader sentiment', value: 4.7 },
    ],
    promo: {
      text: '25% off every evaluation account this month — applied automatically at checkout.',
      code: 'CONTEGO25',
      expiry: 'Ends Jun 30, 2026',
    },
    pros: [
      'Flat 90% profit split from day one — no scaling milestones required.',
      'Same-week first payout after a pass (median 24 hours in our 2026 audit).',
      'Generous 6% trailing drawdown vs the 4-5% industry standard.',
      'EAs and news trading allowed on all account types.',
      'Cleanest evaluation dashboard we tested — clear rule countdown and PnL clock.',
    ],
    cons: [
      'No swing-trading account — overnight & weekend holds are restricted.',
      'Eval fee is non-refundable on a failed attempt (resets are paid).',
      'Limited instrument list outside of CME futures and major FX pairs.',
      'Support is email-first; live chat is staffed business hours only.',
    ],
    tiers: [
      { size: '$25K', fee: '$97', target: '6%', drawdown: '$1,250', payout: '90%' },
      { size: '$50K', fee: '$167', target: '6%', drawdown: '$2,500', payout: '90%' },
      { size: '$100K', fee: '$207', target: '6%', drawdown: '$3,000', payout: '90%' },
      { size: '$150K', fee: '$297', target: '6%', drawdown: '$4,500', payout: '90%' },
      { size: '$250K', fee: '$517', target: '6%', drawdown: '$6,500', payout: '90%' },
      { size: '$400K', fee: '$897', target: '6%', drawdown: '$7,500', payout: '90%' },
    ],
    rules: [
      { t: 'Profit target', v: '6% on phase 1, 4% on phase 2.' },
      { t: 'Trailing drawdown', v: '6% of starting balance, locks at +6% in profit.' },
      { t: 'Daily loss limit', v: 'None on funded accounts.' },
      { t: 'Minimum trading days', v: '5 days per phase, no maximum.' },
      { t: 'Consistency rule', v: 'Best day ≤ 30% of total profit on payout.' },
      { t: 'News trading', v: 'Allowed on all instruments.' },
      { t: 'EAs / copy-trading', v: 'Allowed on a single account at a time.' },
      { t: 'Overnight / weekend', v: 'Closed by Friday 4:55pm ET. No weekend holds.' },
    ],
    platforms: ['NinjaTrader 8', 'TradingView', 'Rithmic', 'Tradovate', 'cTrader'],
    instruments: ['CME futures', 'Index futures', 'Major FX', 'Minor FX', 'Spot metals'],
    payoutMethods: ['ACH (US)', 'Wire transfer', 'Wise', 'Crypto (USDC, USDT)'],
    payoutDetails: {
      first: 'After 8 trading days from funded start',
      cycle: 'Bi-weekly thereafter, or on-demand for $10 fee',
      median: '24 hours from request to wallet',
      minimum: '$100',
    },
    faq: [
      { q: 'How long does the evaluation take?', a: 'Most traders pass phase 1 in 8-14 trading days. There is no maximum time limit, so you can pace the challenge to your style.' },
      { q: 'Are EAs and copy-trading allowed?', a: 'Yes, on a single funded account at a time. Cross-account copy-trading violates the duplicate-trade rule.' },
      { q: 'What happens if I breach a rule?', a: 'A breach on the evaluation closes the attempt — you can pay a discounted reset to retry. On a funded account, your first soft breach issues a warning; a hard breach closes the account.' },
      { q: 'Is the eval fee refunded if I pass?', a: 'The fee is rebated with your first profit split. Most traders see it returned within 30 days of being funded.' },
      { q: 'Can I run multiple accounts?', a: 'Up to three funded accounts can be combined under the scaling plan. Total max funding caps at $1.5M across linked accounts.' },
      { q: 'Where is Apex Edge regulated?', a: 'Apex Edge operates as a US-domiciled tech provider, not a regulated broker — the same structure as most prop firms in 2026.' },
    ],
    sentiment: {
      positive: 78,
      neutral: 14,
      negative: 8,
      sample: [
        { quote: 'First payout hit my Wise account 19 hours after I requested it. Cleanest payout flow I have used.', author: 'Marcus T.', tag: 'Funded, $100K' },
        { quote: 'Phase 1 felt fair — 6% target without a daily loss cap is unusual in a good way.', author: 'Priya R.', tag: 'Funded, $50K' },
        { quote: 'Wish they had a swing account. I trade end-of-day continuation, so the no-overnight rule cost me.', author: 'Daniel K.', tag: 'Evaluation, $25K' },
      ],
    },
    verdictTitle: 'A volume leader for futures traders.',
    verdictBody: 'Apex Edge Capital earns one of our highest 2026 scores on the strength of three things: payouts that consistently clear in under a day, a transparent rulebook, and the most generous trailing drawdown in the futures bracket. We\'d point new prop traders here over any one-step competitor — provided their style fits the no-overnight rule.',
    verdictQuote: 'The cleanest payout flow we tested in 2026 — and the rulebook reads like it was written by a trader.',
    overviewBody: [
      'Apex Edge Capital is a 2021-founded futures + forex prop firm headquartered in Austin, Texas. Its evaluation model is a standard two-step challenge with a 6% profit target and a generous trailing drawdown — but what sets it apart is operational reliability. In our 2026 audit, Apex Edge Capital cleared 24-hour payouts on 98% of requests we tracked, and didn\'t miss a scheduled cycle once over twelve months.',
      'The flat 90/10 split from the first dollar means traders don\'t have to scale through milestone tiers to access better economics — a meaningful improvement over the 70%-rising-to-90% structure that\'s become the industry norm. We\'d recommend it as a default for any futures day-trader looking for their first funded account in 2026.',
    ],
    related: [
      { id: 'pinnacle-prop', name: 'Pinnacle Prop Trading', initials: 'PP', rating: 4.7, tagline: 'One-step model with an 8% drawdown buffer.', funding: '$300K', rank: 2 },
      { id: 'vertex-funded', name: 'Vertex Funded', initials: 'VF', rating: 4.6, tagline: 'Same-day payouts for futures day-traders.', funding: '$250K', rank: 3 },
      { id: 'helios-funded', name: 'Helios Funded', initials: 'HF', rating: 4.4, tagline: 'Crypto-first prop firm with $5M scaling.', funding: '$200K', rank: 6 },
    ],
    publisher: { name: 'Contego Editorial', role: 'Editorial team', date: 'May 14, 2026' },
    credits: [
      { role: 'Written by', name: 'Sheperd Morena', title: 'Head of Content' },
      { role: 'Edited by', name: 'Naya Halim', title: 'Managing Editor' },
      { role: 'Fact checked by', name: 'David Chen', title: 'Research Lead' },
    ],
  },
}

export const TOC_ITEMS = [
  { id: 'verdict', label: 'Editorial verdict' },
  { id: 'overview', label: 'Overview' },
  { id: 'pros-cons', label: 'Pros & cons' },
  { id: 'tiers', label: 'Account tiers' },
  { id: 'rules', label: 'Trading rules' },
  { id: 'payouts', label: 'Profit split & payouts' },
  { id: 'platforms', label: 'Platforms & instruments' },
  { id: 'promo', label: 'Discount & promos' },
  { id: 'sentiment', label: 'Trader sentiment' },
  { id: 'faq', label: 'FAQ' },
  { id: 'related', label: 'Related firms' },
]
