export const COMPETITORS = {
  growyourpropfirm: {
    slug: 'growyourpropfirm',
    name: 'GrowYourPropFirm',
    short: 'GYPF',
    initials: 'GY',
    logo: '/assets/competitors/gypf-logo.png',
    url: 'https://www.growyourpropfirm.com/',
    featureTable: [
      {
        sectionName: 'Strategic Fit',
        rows: [
          { label: 'Prop firm specialization', contego: 'yes', competitor: 'yes' },
          { label: 'Trust-led positioning', contego: 'yes', competitor: 'partial' },
          { label: 'Content-led acquisition focus', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Service Scope',
        rows: [
          { label: 'SEO strategy', contego: 'yes', competitor: 'yes' },
          { label: 'Social media management', contego: 'yes', competitor: 'partial' },
          { label: 'AI UGC video system', contego: 'yes', competitor: 'no' },
          { label: 'Paid ads support', contego: 'partial', competitor: 'yes' },
          { label: 'Landing page messaging', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Content & Creative',
        rows: [
          { label: 'Short-form video scripts', contego: 'yes', competitor: 'partial' },
          { label: 'Hook testing system', contego: 'yes', competitor: 'partial' },
          { label: 'AI content guardrails', contego: 'yes', competitor: 'no' },
          { label: 'Brand voice control', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Best Fit',
        rows: [
          { label: 'Best for trust-aware content growth', contego: 'yes', competitor: 'partial' },
          { label: 'Best for SEO, social, and AI UGC together', contego: 'yes', competitor: 'no' },
          { label: 'Best for broader digital marketing support', contego: 'partial', competitor: 'yes' },
        ],
      },
    ],
    verdictIntro: 'Choose Contego if you want content that turns search intent into trader demand. GrowYourPropFirm can make sense if you want a broader marketing partner for prop firm growth.',
    pickContego: [
      'SEO shaped around prop firm search intent',
      'Social content that explains your offer clearly',
      'AI UGC video without fake trader stories',
      'Landing page copy that reduces confusion',
    ],
    pickThem: [
      'A broader digital marketing partner',
      'More focus on paid ads and general growth campaigns',
      'A service mix that is less centered on AI UGC video',
      'A wider agency approach beyond content systems',
      'A familiar option in the prop firm marketing space',
    ],
    faqItems: [
      { q: 'Is Contego a GrowYourPropFirm alternative?', a: 'Yes. Contego is a GrowYourPropFirm alternative for prop firms that want SEO, social content, AI UGC video, and landing page copy in one focused content system.' },
      { q: 'How is Contego different from GrowYourPropFirm?', a: 'GrowYourPropFirm has a broader digital marketing offer that includes SEO, paid ads, content creation, and brand building. Contego is more focused on content-led acquisition through search intent, social content, AI UGC video, and clearer landing page messaging.' },
      { q: 'Which one is better for AI UGC video?', a: 'Choose Contego if AI UGC video is a priority. Contego brings AI UGC into the core system, turning your offers, rules, FAQs, objections, and proof points into short-form videos for social, ads, and landing pages.' },
      { q: 'Which one is better for SEO?', a: 'Both can support SEO. Contego is the better fit if you want SEO content shaped around what traders search before buying, including rules, payouts, reviews, comparisons, platforms, and alternatives.' },
      { q: 'Which one is better for paid ads?', a: 'GrowYourPropFirm may be the better fit if paid media buying is your main priority. Contego supports paid campaigns through sharper landing page copy, ad angles, AI UGC scripts, and content assets, but paid ad management is not the core offer.' },
      { q: 'Why choose Contego over GrowYourPropFirm?', a: 'Choose Contego if you want a leaner content system focused on search intent, social trust, AI UGC video, and landing pages that explain your offer clearly before people decide.' },
      { q: 'Can Contego replace GrowYourPropFirm?', a: 'Yes, if your main need is content-led growth. Contego can handle SEO content, social media content, AI UGC video, landing page copy, and offer messaging.' },
      { q: 'Does Contego guarantee better results than GrowYourPropFirm?', a: 'No. Contego does not guarantee rankings, sales, or challenge purchases. The focus is on making your prop firm easier to find, understand, and trust through stronger content.' },
    ],
  },

  yourpropfirm: {
    slug: 'yourpropfirm',
    name: 'YourPropFirm',
    short: 'YPF',
    initials: 'YP',
    logo: '/assets/competitors/ypf-logo.svg',
    url: 'https://yourpropfirm.com/',
    featureTable: [
      {
        sectionName: 'Strategic Fit',
        rows: [
          { label: 'Prop firm specialization', contego: 'yes', competitor: 'yes' },
          { label: 'Primary marketing agency focus', contego: 'yes', competitor: 'partial' },
          { label: 'Content-led acquisition focus', contego: 'yes', competitor: 'partial' },
          { label: 'Operating system for prop firms', contego: 'no', competitor: 'yes' },
          { label: 'Best for launch infrastructure', contego: 'no', competitor: 'yes' },
          { label: 'Best for marketing execution', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Service Scope',
        rows: [
          { label: 'SEO strategy', contego: 'yes', competitor: 'partial' },
          { label: 'Social media management', contego: 'yes', competitor: 'partial' },
          { label: 'AI UGC video system', contego: 'yes', competitor: 'no' },
          { label: 'Landing page messaging', contego: 'yes', competitor: 'partial' },
          { label: 'Trading platform support', contego: 'no', competitor: 'yes' },
          { label: 'CRM and dashboard infrastructure', contego: 'no', competitor: 'yes' },
          { label: 'Risk, payouts, and operational tools', contego: 'no', competitor: 'yes' },
        ],
      },
      {
        sectionName: 'Content & Creative',
        rows: [
          { label: 'Search intent content', contego: 'yes', competitor: 'partial' },
          { label: 'Short-form video scripts', contego: 'yes', competitor: 'partial' },
          { label: 'Hook testing system', contego: 'yes', competitor: 'no' },
          { label: 'AI UGC video workflow', contego: 'yes', competitor: 'no' },
          { label: 'Offer explainer content', contego: 'yes', competitor: 'partial' },
          { label: 'Brand voice control', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Trust & Brand Control',
        rows: [
          { label: 'Trust-aware messaging', contego: 'yes', competitor: 'partial' },
          { label: 'Fake proof avoidance', contego: 'yes', competitor: 'partial' },
          { label: 'AI UGC without fake testimonials', contego: 'yes', competitor: 'no' },
          { label: 'Claims and proof handling', contego: 'yes', competitor: 'partial' },
          { label: 'Trader psychology focus', contego: 'yes', competitor: 'partial' },
          { label: 'Clear expectation-setting content', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Best Fit',
        rows: [
          { label: 'Best for SEO, social, and AI UGC together', contego: 'yes', competitor: 'no' },
          { label: 'Best for marketing content systems', contego: 'yes', competitor: 'partial' },
          { label: 'Best for tech stack and operations', contego: 'no', competitor: 'yes' },
          { label: 'Best for launching a prop firm infrastructure', contego: 'no', competitor: 'yes' },
          { label: 'Best for clearer buyer-facing content', contego: 'yes', competitor: 'partial' },
        ],
      },
    ],
    verdictIntro: 'Choose Contego if you need a focused prop firm marketing agency, not a full operating system. YourPropFirm can make sense if your priority is infrastructure, dashboard technology, trading platform setup, CRM, risk tools, payouts, and operational support.',
    pickContego: [
      'SEO shaped around prop firm search intent',
      'Social content that explains your offer clearly',
      'AI UGC video without fake trader stories',
      'Landing page copy that reduces confusion',
      'A focused prop firm marketing agency',
      'Content that turns buyer questions into growth assets',
    ],
    pickThem: [
      'Prop firm dashboard and CRM infrastructure',
      'Trading platform integrations',
      'Risk, payout, and operational tools',
      'A wider operating system for launching or running a firm',
      'Marketing as part of a broader infrastructure package',
    ],
    faqItems: [
      { q: 'Is Contego a YourPropFirm alternative?', a: 'Yes, if you are comparing marketing support. Contego is a YourPropFirm alternative for prop firms that need SEO, social content, AI UGC video, and landing page copy. If you need dashboard technology, CRM, trading platform setup, risk tools, or payout infrastructure, YourPropFirm may be closer to what you are looking for.' },
      { q: 'How is Contego different from YourPropFirm?', a: 'YourPropFirm is positioned as a complete operating system and tech stack for prop firms. Contego is a focused prop firm marketing agency. Contego helps with buyer-facing content: SEO pages, social posts, AI UGC videos, landing page copy, offer messaging, and content that answers trader questions before they buy.' },
      { q: 'Which one is better for marketing?', a: 'Choose Contego if your main priority is marketing content, search intent, social media, AI UGC video, and landing page copy. Choose YourPropFirm if you want marketing as part of a wider infrastructure package that also includes tools for launching, operating, and managing a prop firm.' },
      { q: 'Which one is better for AI UGC video?', a: 'Contego is the stronger fit for AI UGC video. Contego brings AI UGC into the core content system, turning your offers, rules, FAQs, objections, and proof points into short-form videos for social, ads, and landing pages.' },
      { q: 'Which one is better for launching a prop firm?', a: 'YourPropFirm may be the better fit if you need the backend system to launch or operate a prop firm, including dashboard infrastructure, platform integrations, CRM, payouts, risk, and related services. Contego is the better fit after or during launch if you need the marketing content system that helps people find, understand, and choose your firm.' },
      { q: 'Which one is better for SEO?', a: 'Choose Contego if you want SEO shaped around buyer search intent, including rules, payouts, reviews, comparisons, platforms, alternatives, and offer clarity. YourPropFirm may offer marketing support, but Contego is more focused on SEO content as a growth asset.' },
      { q: 'Can Contego work with firms already using YourPropFirm?', a: 'Yes. Contego can support prop firms that already use YourPropFirm or another backend provider. YourPropFirm can power the operational side of the business, while Contego supports the marketing side with SEO, social content, AI UGC video, and landing page copy.' },
      { q: 'Why choose Contego over YourPropFirm?', a: 'Choose Contego if you do not need a full prop firm operating system and only want a focused agency for marketing execution. Contego is designed for prop firms that need clearer content, stronger search visibility, more useful social posts, AI UGC video, and landing pages that answer buyer questions.' },
      { q: 'Does Contego guarantee better results than YourPropFirm?', a: 'No. Contego does not guarantee rankings, sales, or challenge purchases. The focus is on making your prop firm easier to find, understand, and trust through stronger content across search, social, video, and landing pages.' },
    ],
  },

  'propfirmmarketing-agency': {
    slug: 'propfirmmarketing-agency',
    name: 'PropFirmMarketing.Agency',
    short: 'PFMA',
    initials: 'PF',
    logo: '/assets/competitors/pfma-logo.webp',
    url: 'https://www.propfirmmarketing.agency/',
    featureTable: [
      {
        sectionName: 'Strategic Fit',
        rows: [
          { label: 'Prop firm specialization', contego: 'yes', competitor: 'yes' },
          { label: 'Primary marketing agency focus', contego: 'yes', competitor: 'yes' },
          { label: 'Trust-led positioning', contego: 'yes', competitor: 'partial' },
          { label: 'Content-led acquisition focus', contego: 'yes', competitor: 'partial' },
          { label: 'Best for focused content systems', contego: 'yes', competitor: 'partial' },
          { label: 'Best for broader digital marketing support', contego: 'partial', competitor: 'yes' },
        ],
      },
      {
        sectionName: 'Service Scope',
        rows: [
          { label: 'SEO strategy', contego: 'yes', competitor: 'yes' },
          { label: 'Social media content', contego: 'yes', competitor: 'yes' },
          { label: 'AI UGC video system', contego: 'yes', competitor: 'no' },
          { label: 'Landing page messaging', contego: 'yes', competitor: 'partial' },
          { label: 'Paid ads support', contego: 'partial', competitor: 'yes' },
          { label: 'Web design support', contego: 'partial', competitor: 'yes' },
          { label: 'Email marketing', contego: 'no', competitor: 'yes' },
          { label: 'Reputation management', contego: 'partial', competitor: 'yes' },
        ],
      },
      {
        sectionName: 'Content & Creative',
        rows: [
          { label: 'Search intent content', contego: 'yes', competitor: 'yes' },
          { label: 'Short-form video scripts', contego: 'yes', competitor: 'partial' },
          { label: 'Hook testing system', contego: 'yes', competitor: 'partial' },
          { label: 'AI UGC video workflow', contego: 'yes', competitor: 'no' },
          { label: 'Offer explainer content', contego: 'yes', competitor: 'partial' },
          { label: 'Brand voice control', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Trust & Brand Control',
        rows: [
          { label: 'Trust-aware messaging', contego: 'yes', competitor: 'partial' },
          { label: 'Fake proof avoidance', contego: 'yes', competitor: 'partial' },
          { label: 'AI UGC without fake testimonials', contego: 'yes', competitor: 'no' },
          { label: 'Claims and proof handling', contego: 'yes', competitor: 'partial' },
          { label: 'Trader psychology focus', contego: 'yes', competitor: 'partial' },
          { label: 'Clear expectation-setting content', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Best Fit',
        rows: [
          { label: 'Best for SEO, social, and AI UGC together', contego: 'yes', competitor: 'no' },
          { label: 'Best for content-led acquisition', contego: 'yes', competitor: 'partial' },
          { label: 'Best for paid advertising', contego: 'partial', competitor: 'yes' },
          { label: 'Best for web design and email marketing', contego: 'no', competitor: 'yes' },
          { label: 'Best for clearer buyer-facing content', contego: 'yes', competitor: 'partial' },
        ],
      },
    ],
    verdictIntro: 'Choose Contego if you want a sharper content system, not just a wider service menu. PropFirmMarketing.Agency can make sense if you want broader digital marketing support across SEO, paid ads, web design, email marketing, and reputation management.',
    pickContego: [
      'SEO shaped around prop firm search intent',
      'Social content that explains your offer clearly',
      'AI UGC video without fake trader stories',
      'Landing page copy that reduces confusion',
      'A focused content system across search, social, and video',
      'Clearer messaging for rules, payouts, proof, and offers',
    ],
    pickThem: [
      'A broader prop firm marketing agency',
      'Paid ads as a major service focus',
      'Web design and email marketing support',
      'Reputation management services',
      'A wider digital marketing service mix',
      'Less focus on AI UGC as a core system',
    ],
    faqItems: [
      { q: 'Is Contego a PropFirmMarketing.Agency alternative?', a: 'Yes. Contego is a PropFirmMarketing.Agency alternative for prop firms that want SEO, social content, AI UGC video, and landing page copy in one focused content system. PropFirmMarketing.Agency offers a broader digital marketing service mix. Contego is more focused on content-led acquisition across search, social, video, and landing pages.' },
      { q: 'How is Contego different from PropFirmMarketing.Agency?', a: 'PropFirmMarketing.Agency publicly offers services like SEO, paid advertising, content marketing, web design, email marketing, and reputation management. Contego focuses on the buyer-facing content system: search intent SEO, social content, AI UGC video, landing page copy, and message clarity across the buyer journey.' },
      { q: 'Which one is better for AI UGC video?', a: 'Choose Contego if AI UGC video is a priority. Contego brings AI UGC into the core content system, turning your offers, rules, FAQs, objections, and proof points into short-form videos for social, ads, and landing pages.' },
      { q: 'Which one is better for SEO?', a: 'Both can support SEO for prop firms. Choose Contego if you want SEO shaped around buyer questions, search intent, rules, payouts, reviews, comparisons, platforms, alternatives, and offer clarity. Choose PropFirmMarketing.Agency if you want a broader SEO scope that may include technical SEO, on-page SEO, off-page SEO, and SEO audits.' },
      { q: 'Which one is better for paid ads?', a: 'PropFirmMarketing.Agency may be the better fit if paid advertising is your main priority. Contego can support paid campaigns through landing page copy, ad angles, AI UGC scripts, and content assets, but paid media buying is not the core offer.' },
      { q: 'Which one is better for web design or email marketing?', a: 'PropFirmMarketing.Agency may be the better fit if you need web design or email marketing as part of the same agency scope. Contego focuses more on SEO content, social content, AI UGC video, landing page messaging, and content clarity.' },
      { q: 'Why choose Contego over PropFirmMarketing.Agency?', a: 'Choose Contego if you want a sharper content system focused on search intent, social trust, AI UGC video, and landing pages that explain your offer clearly. Contego is not trying to be the widest service provider. It is focused on making your prop firm easier to find, understand, and trust through better content.' },
      { q: 'Can Contego replace PropFirmMarketing.Agency?', a: 'Yes, if your main need is content-led acquisition. Contego can support SEO content, social media content, AI UGC video, landing page copy, and offer messaging. If you need full paid media buying, web design, or email marketing under one provider, PropFirmMarketing.Agency may still be worth comparing.' },
      { q: 'Does Contego guarantee better results than PropFirmMarketing.Agency?', a: 'No. Contego does not guarantee rankings, sales, or challenge purchases. The focus is on improving your content system, so traders can find your firm, understand your offer, and make a more confident decision.' },
    ],
  },

  propxgrowth: {
    slug: 'propxgrowth',
    name: 'PropXGrowth',
    short: 'PropXGrowth',
    initials: 'PX',
    logo: null,
    url: 'https://propxgrowth.com/',
    featureTable: [
      {
        sectionName: 'Strategic Fit',
        rows: [
          { label: 'Prop firm specialization', contego: 'yes', competitor: 'yes' },
          { label: 'Primary marketing agency focus', contego: 'yes', competitor: 'yes' },
          { label: 'Search intent focus', contego: 'yes', competitor: 'partial' },
          { label: 'Content-led acquisition focus', contego: 'yes', competitor: 'partial' },
          { label: 'Acquisition campaign focus', contego: 'partial', competitor: 'yes' },
          { label: 'Trust-led messaging', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Service Scope',
        rows: [
          { label: 'SEO strategy', contego: 'yes', competitor: 'partial' },
          { label: 'Social media content', contego: 'yes', competitor: 'partial' },
          { label: 'AI UGC video system', contego: 'yes', competitor: 'no' },
          { label: 'Landing page messaging', contego: 'yes', competitor: 'partial' },
          { label: 'Acquisition campaigns', contego: 'partial', competitor: 'yes' },
          { label: 'Paid growth support', contego: 'partial', competitor: 'yes' },
          { label: 'Compliance-aware positioning', contego: 'yes', competitor: 'yes' },
        ],
      },
      {
        sectionName: 'Content & Creative',
        rows: [
          { label: 'Search intent content', contego: 'yes', competitor: 'partial' },
          { label: 'Short-form video scripts', contego: 'yes', competitor: 'partial' },
          { label: 'Hook testing system', contego: 'yes', competitor: 'partial' },
          { label: 'AI UGC video workflow', contego: 'yes', competitor: 'no' },
          { label: 'Offer explainer content', contego: 'yes', competitor: 'partial' },
          { label: 'Brand voice control', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Trust & Brand Control',
        rows: [
          { label: 'Trust-aware messaging', contego: 'yes', competitor: 'partial' },
          { label: 'Fake proof avoidance', contego: 'yes', competitor: 'partial' },
          { label: 'AI UGC without fake testimonials', contego: 'yes', competitor: 'no' },
          { label: 'Claims and proof handling', contego: 'yes', competitor: 'partial' },
          { label: 'Trader psychology focus', contego: 'yes', competitor: 'partial' },
          { label: 'Clear expectation-setting content', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Best Fit',
        rows: [
          { label: 'Best for SEO, social, and AI UGC together', contego: 'yes', competitor: 'no' },
          { label: 'Best for content-led acquisition', contego: 'yes', competitor: 'partial' },
          { label: 'Best for acquisition campaigns', contego: 'partial', competitor: 'yes' },
          { label: 'Best for paid growth direction', contego: 'partial', competitor: 'yes' },
          { label: 'Best for clearer buyer-facing content', contego: 'yes', competitor: 'partial' },
        ],
      },
    ],
    verdictIntro: 'Choose Contego if you want a clearer content system, not only acquisition campaigns. PropXGrowth can make sense if you want an agency focused on acquisition campaigns, performance messaging, and growth positioning for prop firms.',
    pickContego: [
      'SEO shaped around prop firm search intent',
      'Social content that explains your offer clearly',
      'AI UGC video without fake trader stories',
      'Landing page copy that reduces confusion',
      'A focused content system across search, social, and video',
      'Clearer messaging for rules, payouts, proof, and offers',
    ],
    pickThem: [
      'Acquisition marketing as the main focus',
      'Campaign-led growth support',
      'Paid growth direction',
      'Performance-focused positioning',
      'A marketing partner focused on scaling funded trader acquisition',
      'Less focus on AI UGC as a core system',
    ],
    faqItems: [
      { q: 'Is Contego a PropXGrowth alternative?', a: 'Yes. Contego is a PropXGrowth alternative for prop firms that want SEO, social content, AI UGC video, and landing page copy in one focused content system. PropXGrowth appears more focused on acquisition marketing and campaign-led growth. Contego is more focused on content-led acquisition across search, social, video, and landing pages.' },
      { q: 'How is Contego different from PropXGrowth?', a: 'PropXGrowth positions itself around elite acquisition marketing, data-driven campaigns, compliance, and long-term brand authority for prop firms. Contego focuses on the buyer-facing content system: search intent SEO, social media content, AI UGC video, landing page messaging, and clearer offer explanation.' },
      { q: 'Which one is better for AI UGC video?', a: 'Choose Contego if AI UGC video is a priority. Contego brings AI UGC into the core content system, turning your offers, rules, FAQs, objections, and proof points into short-form videos for social, ads, and landing pages.' },
      { q: 'Which one is better for SEO?', a: 'Choose Contego if you want SEO shaped around buyer questions, search intent, rules, payouts, reviews, comparisons, platforms, alternatives, and offer clarity. PropXGrowth may support growth campaigns, but AI UGC and search-intent content are stronger Contego differentiators.' },
      { q: 'Which one is better for acquisition campaigns?', a: 'PropXGrowth may be the better fit if your main need is campaign-led acquisition and paid growth direction. Contego can support acquisition through SEO content, social content, landing page copy, AI UGC scripts, and offer messaging, but paid campaign management is not the core offer.' },
      { q: 'Why choose Contego over PropXGrowth?', a: 'Choose Contego if you want a sharper content system focused on search intent, social trust, AI UGC video, and landing pages that explain your offer clearly. Contego is a better fit when your firm needs content that answers buyer questions before traders compare you with another firm.' },
      { q: 'Can Contego replace PropXGrowth?', a: 'Yes, if your main need is content-led acquisition. Contego can support SEO content, social media content, AI UGC video, landing page copy, and offer messaging. If you need a campaign-led acquisition partner with paid growth as the main focus, PropXGrowth may still be worth comparing.' },
      { q: 'Does Contego guarantee better results than PropXGrowth?', a: 'No. Contego does not guarantee rankings, sales, or challenge purchases. The focus is on improving your content system, so traders can find your firm, understand your offer, and make a more confident decision.' },
    ],
  },

  aim: {
    slug: 'aim',
    name: 'AIM',
    short: 'AIM',
    initials: 'AI',
    logo: '/assets/competitors/aim-logo.png',
    url: 'https://aimcompany.co/',
    featureTable: [
      {
        sectionName: 'Strategic Fit',
        rows: [
          { label: 'Prop firm specialization', contego: 'yes', competitor: 'yes' },
          { label: 'Primary marketing agency focus', contego: 'yes', competitor: 'yes' },
          { label: 'Search intent focus', contego: 'yes', competitor: 'partial' },
          { label: 'Content-led acquisition focus', contego: 'yes', competitor: 'partial' },
          { label: 'Email marketing focus', contego: 'partial', competitor: 'yes' },
          { label: 'Affiliate and IB growth focus', contego: 'no', competitor: 'yes' },
        ],
      },
      {
        sectionName: 'Service Scope',
        rows: [
          { label: 'SEO strategy', contego: 'yes', competitor: 'partial' },
          { label: 'Social media content', contego: 'yes', competitor: 'yes' },
          { label: 'AI UGC video system', contego: 'yes', competitor: 'partial' },
          { label: 'Landing page messaging', contego: 'yes', competitor: 'partial' },
          { label: 'Email marketing systems', contego: 'partial', competitor: 'yes' },
          { label: 'Affiliate network support', contego: 'no', competitor: 'yes' },
          { label: 'Influencer growth support', contego: 'no', competitor: 'yes' },
          { label: 'Funnel support', contego: 'partial', competitor: 'yes' },
        ],
      },
      {
        sectionName: 'Content & Creative',
        rows: [
          { label: 'Search intent content', contego: 'yes', competitor: 'partial' },
          { label: 'Short-form video scripts', contego: 'yes', competitor: 'partial' },
          { label: 'Hook testing system', contego: 'yes', competitor: 'partial' },
          { label: 'AI UGC video workflow', contego: 'yes', competitor: 'partial' },
          { label: 'Offer explainer content', contego: 'yes', competitor: 'partial' },
          { label: 'Brand voice control', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Trust & Brand Control',
        rows: [
          { label: 'Trust-aware messaging', contego: 'yes', competitor: 'partial' },
          { label: 'Fake proof avoidance', contego: 'yes', competitor: 'partial' },
          { label: 'AI UGC without fake testimonials', contego: 'yes', competitor: 'partial' },
          { label: 'Claims and proof handling', contego: 'yes', competitor: 'partial' },
          { label: 'Trader psychology focus', contego: 'yes', competitor: 'yes' },
          { label: 'Clear expectation-setting content', contego: 'yes', competitor: 'partial' },
        ],
      },
      {
        sectionName: 'Best Fit',
        rows: [
          { label: 'Best for SEO, social, and AI UGC together', contego: 'yes', competitor: 'partial' },
          { label: 'Best for content-led acquisition', contego: 'yes', competitor: 'partial' },
          { label: 'Best for email marketing systems', contego: 'partial', competitor: 'yes' },
          { label: 'Best for affiliate and IB networks', contego: 'no', competitor: 'yes' },
          { label: 'Best for clearer buyer-facing content', contego: 'yes', competitor: 'partial' },
          { label: 'Best for wider trading brand growth infrastructure', contego: 'partial', competitor: 'yes' },
        ],
      },
    ],
    verdictIntro: 'Choose Contego if you want search, social, AI UGC, and landing page copy working as one content system. AIM can make sense if your main priority is email marketing, affiliate growth, influencer growth, and wider marketing infrastructure for a trading brand.',
    pickContego: [
      'SEO shaped around prop firm search intent',
      'Social content that explains your offer clearly',
      'AI UGC video without fake trader stories',
      'Landing page copy that reduces confusion',
      'A focused content system across search, social, and video',
      'Clearer messaging for rules, payouts, proof, and offers',
    ],
    pickThem: [
      'Email marketing systems as a core service',
      'Affiliate or IB network support',
      'Influencer growth support',
      'Funnel and automation support',
      'A wider growth infrastructure partner for trading brands',
      'Less focus on SEO, landing page copy, and AI UGC as one content system',
    ],
    faqItems: [
      { q: 'Is Contego an AIM alternative?', a: 'Yes. Contego is an AIM alternative for prop firms that want SEO, social content, AI UGC video, and landing page copy in one focused content system. AIM is more focused on wider trading brand growth infrastructure, including email marketing, affiliate networks, social media, funnels, AI tools, and influencer growth.' },
      { q: 'How is Contego different from AIM?', a: 'AIM positions itself around email systems, affiliate networks, social media, content, funnels, AI tools, and influencer growth for trading brands. Contego focuses on the buyer-facing content system: search intent SEO, social media content, AI UGC video, landing page messaging, and clearer offer explanation.' },
      { q: 'Which one is better for AI UGC video?', a: 'Choose Contego if AI UGC video is a priority. Contego brings AI UGC into the core content system, turning your offers, rules, FAQs, objections, and proof points into short-form videos for social, ads, and landing pages.' },
      { q: 'Which one is better for SEO?', a: 'Choose Contego if you want SEO shaped around buyer questions, search intent, rules, payouts, reviews, comparisons, platforms, alternatives, and offer clarity. AIM may support broader marketing infrastructure, but Contego is more focused on SEO content as part of a connected acquisition system.' },
      { q: 'Which one is better for email marketing?', a: 'AIM may be the better fit if email marketing is your main priority. Contego can support email-adjacent messaging through landing page copy, content angles, and offer clarity, but email automation is not the core offer.' },
      { q: 'Which one is better for affiliate or IB growth?', a: 'AIM may be the better fit if your main need is affiliate or IB network management. Contego focuses more on SEO pages, social content, AI UGC video, landing page copy, and buyer-facing messaging.' },
      { q: 'Why choose Contego over AIM?', a: 'Choose Contego if you want a sharper content system focused on search intent, social content, AI UGC video, and landing pages that explain your offer clearly. Contego is a stronger fit when your firm needs content that helps people find, understand, and trust your prop firm before they compare other options.' },
      { q: 'Can Contego replace AIM?', a: 'Yes, if your main need is content-led acquisition. Contego can support SEO content, social media content, AI UGC video, landing page copy, and offer messaging. If your priority is email marketing, affiliate networks, or influencer growth, AIM may still be worth comparing.' },
      { q: 'Does Contego guarantee better results than AIM?', a: 'No. Contego does not guarantee rankings, sales, or challenge purchases. The focus is on making your prop firm easier to find, understand, and trust through stronger content across search, social, video, and landing pages.' },
    ],
  },
}
