export const SERVICE_DATA = {
  seo: {
    slug: 'seo',
    num: '01',
    label: 'SEO',
    eyebrow: 'Programmatic SEO',
    h1Pre: 'SEO that ranks for',
    h1Accent: 'buyer intent.',
    lead: 'Topical authority across every prop-firm review, comparison, and "best of" query — engineered to outrank affiliates and own the funnel.',
    cta: { primary: 'Get an SEO audit', secondary: 'See pricing' },
    stats: [
      { n: '90k', l: 'organic visits / mo (avg client, m11)' },
      { n: '<14d', l: 'first page launch' },
      { n: '4.2x', l: 'CPC saved vs paid' },
    ],
    startsAt: {
      price: '$6,400',
      per: '/ month',
      title: 'SEO Engine — month-to-month, no lock-in.',
      desc: 'Includes the full programmatic stack, weekly publishing cadence, off-page link-building, and reporting. Setup completed in week one.',
    },
    includes: [
      { i: 'pages', t: 'Programmatic landing pages', d: 'Templated comparison, review, and "best for X" pages — generated and QA\'d in batches of 20 weekly.' },
      { i: 'kw', t: 'Buyer-intent keyword maps', d: 'Full evaluation, instrument, and challenge-type taxonomy mapped to your funnel and competitors.' },
      { i: 'link', t: 'Digital PR + backlinks', d: 'Earned mentions on Tier-1 finance media. Targeted outreach to Investopedia-adjacent publications.' },
      { i: 'tech', t: 'Tech SEO & Core Web Vitals', d: 'Schema, hreflang, internal link graph, sitemap automation, and Lighthouse 95+ baseline.' },
      { i: 'edit', t: 'Editorial articles, weekly', d: '2,000-word evergreen pieces written by operators who actually trade prop. No SEO content farms.' },
      { i: 'rep', t: 'Reporting & rank tracking', d: 'Weekly dashboard with rank movement, traffic, signups attributable to organic, and next-quarter bets.' },
    ],
    process: [
      { week: 'Week 1', t: 'Audit & strategy', d: 'Full crawl, competitor teardown, keyword universe sized, and the first 60 pages mapped.' },
      { week: 'Week 2', t: 'Stack & first batch', d: 'Templates built, technical baseline fixed, and the first 20 programmatic pages go live.' },
      { week: 'Week 3–4', t: 'Ramp publishing', d: '20 new pages/week + 2 editorial features/week. Outreach engine starts dialing.' },
      { week: 'Month 2+', t: 'Compound', d: 'Weekly rank reviews, monthly retro, link velocity scales. We double down on what indexes.' },
    ],
    compare: {
      themLabel: 'In-house',
      usLabel: 'With Contego',
      rows: [
        { axis: 'Time to first published page', them: '4–8 weeks', us: '< 14 days' },
        { axis: 'Publishing cadence', them: '2–4 pages / month', us: '20 pages / week' },
        { axis: 'Backlink building', them: 'One-off, founder-led', us: 'Automated PR pipeline' },
        { axis: 'Technical SEO baseline', them: 'Patched ad-hoc', us: 'Lighthouse 95+ guaranteed' },
        { axis: 'Reporting cadence', them: 'Quarterly, manual', us: 'Weekly dashboard + retros' },
        { axis: 'Hiring overhead', them: '3–4 FTEs, ~$45k/mo', us: 'One fixed retainer' },
      ],
    },
    faq: [
      { q: 'How quickly will we see ranking movement?', a: 'Long-tail buyer-intent keywords typically rank within 4–6 weeks. Competitive head terms compound from month 3 onward — that\'s when the programmatic stack starts pulling its weight.' },
      { q: 'Do you write the content yourselves?', a: 'Yes. Every editorial piece is written by an operator on our team — not subcontracted to writers who have never traded. We use AI for outlining and fact-checking, never for drafts.' },
      { q: 'What does the technical SEO baseline include?', a: 'Schema markup, hreflang, internal link graph, sitemap automation, image optimization, Core Web Vitals to Lighthouse 95+, and a redirect map for every page we ship.' },
      { q: 'How do you handle regulated finance topics?', a: 'We have a compliance review step before every page ships. Disclaimers, risk warnings, and jurisdictional footers are templated and audited monthly.' },
      { q: 'Can we start with just an audit?', a: 'Yes — we offer a one-time audit + roadmap at $2,400 that you can apply against the first month of retainer if you sign on.' },
    ],
  },
  social: {
    slug: 'social',
    num: '02',
    label: 'Social',
    eyebrow: 'Social Media Management',
    h1Pre: 'Social that turns lurkers into',
    h1Accent: 'funded traders.',
    lead: 'Daily posting, real community ops, and creator-grade content across Twitter, IG, TikTok, and YouTube — built to convert, not to look busy.',
    cta: { primary: 'Book a strategy call', secondary: 'See pricing' },
    stats: [
      { n: '120+', l: 'posts shipped per month' },
      { n: '4', l: 'channels managed' },
      { n: '<8h', l: 'reply SLA' },
    ],
    startsAt: {
      price: '$4,800',
      per: '/ month',
      title: 'Social Engine — full-stack channel ops.',
      desc: 'Calendar, original creative, daily posting, community DMs, and weekly performance retros. Add channels at $1,200/mo each.',
    },
    includes: [
      { i: 'cal', t: 'Content calendar, weekly', d: 'Built around your launches, market events, and the cultural moments that move trader audiences.' },
      { i: 'design', t: 'Original creative, daily', d: 'Graphics, motion, carousels, and reels — designed in-brand, not pulled from a stock library.' },
      { i: 'comm', t: 'Community management', d: 'Replies, DMs, and quote-tweets handled by trader-fluent humans. Under 8-hour weekday SLA.' },
      { i: 'cre', t: 'Creator partnerships', d: 'We source, brief, and ship paid + organic creator drops. You approve, we coordinate end-to-end.' },
      { i: 'data', t: 'Cross-channel analytics', d: 'Unified weekly view of reach, signups, and revenue attributed by channel — not vanity metrics.' },
      { i: 'cris', t: 'Crisis & comms playbook', d: 'On-call drafting for evaluation failures, payout delays, or platform-wide market events.' },
    ],
    process: [
      { week: 'Week 1', t: 'Brand & voice intake', d: 'Tone audit, channel-by-channel benchmarks, and a 90-day calendar mapped to launches.' },
      { week: 'Week 2', t: 'First wave ships', d: 'First 20 posts live across primary channels. Community ops handoff complete.' },
      { week: 'Week 3–4', t: 'Full cadence', d: '30+ posts/month per channel, daily community ops, weekly creator briefs going out.' },
      { week: 'Month 2+', t: 'Optimize', d: 'Hooks, formats, and posting windows refined against signup attribution — not likes.' },
    ],
    compare: {
      themLabel: 'In-house',
      usLabel: 'With Contego',
      rows: [
        { axis: 'Posts shipped per month', them: '20–30', us: '120+' },
        { axis: 'Channels covered', them: '1–2 (usually X only)', us: 'X, IG, TikTok, YouTube' },
        { axis: 'Reply / DM SLA', them: '24–48h, inconsistent', us: '< 8 hours, weekdays' },
        { axis: 'Creator coordination', them: 'Founder DMs creators', us: 'Full briefing + paperwork' },
        { axis: 'Original creative', them: 'Canva, ad-hoc', us: 'In-brand design system' },
        { axis: 'Hiring overhead', them: '2 FTEs + freelance, ~$28k/mo', us: 'One fixed retainer' },
      ],
    },
    faq: [
      { q: 'Which channels do you cover by default?', a: 'X (Twitter), Instagram, TikTok, and YouTube Shorts are included in the base retainer. LinkedIn and Threads are add-ons at $1,200/mo each.' },
      { q: 'Do you handle paid social as well?', a: 'Organic and community ops are included. Paid media management is a separate retainer — we can refer or run it in-house depending on spend.' },
      { q: 'Who actually replies to our DMs?', a: 'A small pod of trader-fluent community managers — never offshored, never bots. We hand-off escalations to your team within an agreed playbook.' },
      { q: 'Can we approve every post before it goes live?', a: 'Yes. We default to a 48-hour approval window with batch review, but you can opt for full pre-approval if compliance requires it.' },
      { q: 'What if something goes wrong on a platform?', a: 'You get an on-call drafting line. Evaluation failures, payout delays, or platform outages get a response within 90 minutes during business hours.' },
    ],
  },
  ugc: {
    slug: 'ugc',
    num: '03',
    label: 'AI UGC',
    eyebrow: 'AI UGC Video',
    h1Pre: 'AI UGC video at',
    h1Accent: 'creator scale.',
    lead: 'Native-feeling vertical creator videos, generated and edited daily. Test 50 hooks a week — without paying 50 creators or waiting on shoots.',
    cta: { primary: 'See a sample reel', secondary: 'See pricing' },
    stats: [
      { n: '50+', l: 'hooks tested weekly' },
      { n: '< 72h', l: 'concept to live' },
      { n: '9:16', l: 'native vertical, captions on' },
    ],
    startsAt: {
      price: '$7,200',
      per: '/ month',
      title: 'UGC Engine — 50 hooks / week, end-to-end.',
      desc: 'Includes scripting, AI generation, editing, captioning, compliance review, and weekly performance retros. Ready for paid social out of the box.',
    },
    includes: [
      { i: 'script', t: 'Hook scripting at volume', d: '50+ hooks per week, written by direct-response copywriters who understand prop-firm psychology.' },
      { i: 'gen', t: 'AI generation pipeline', d: 'Proprietary stack across HeyGen, Pika, Sora, and Runway — picked per hook for the right output quality.' },
      { i: 'edit', t: 'Human-in-the-loop editing', d: 'Every video reviewed and finished by a video editor. Cuts, captions, B-roll, sound design.' },
      { i: 'comp', t: 'Compliance & ad approval', d: 'Pre-cleared against Meta, TikTok, and YouTube ad policy. We re-shoot anything that won\'t pass.' },
      { i: 'feed', t: 'Native-feeling output', d: 'Vertical 9:16, native captions, platform-current music — built to disappear into the For You page.' },
      { i: 'rep', t: 'Weekly hook performance', d: 'Dashboard of CTR, hook-rate, and signups per video — winners scaled, losers retired automatically.' },
    ],
    process: [
      { week: 'Week 1', t: 'Brief & avatars', d: 'Audience deep-dive, custom AI avatars trained, first hook bank of 200 drafted.' },
      { week: 'Week 2', t: 'First wave', d: '50 videos shipped, compliance pass, first paid-test cohort handed to media.' },
      { week: 'Week 3–4', t: 'Full cadence', d: '50 hooks/week steady-state. Winners cut into long-form variants and platform crossposts.' },
      { week: 'Month 2+', t: 'Scale & retire', d: 'Hook DNA analyzed weekly. We retire fatigued formats and double down on the patterns that buy.' },
    ],
    compare: {
      themLabel: 'Traditional UGC',
      usLabel: 'With Contego',
      rows: [
        { axis: 'Hooks tested per week', them: '2–5', us: '50+' },
        { axis: 'Cost per video', them: '$200–$600', us: '$28' },
        { axis: 'Concept-to-live time', them: '2–4 weeks', us: '< 72 hours' },
        { axis: 'Creator coordination', them: 'Manual, fragile', us: 'Pipelined, repeatable' },
        { axis: 'Ad-policy compliance', them: 'Hope & pray', us: 'Pre-cleared' },
        { axis: 'Reshoots when something fails', them: 'Slow, expensive', us: 'Same-day regen' },
      ],
    },
    faq: [
      { q: 'Are these "AI influencers" or real creators?', a: 'AI-generated avatars, trained on direct-response performance patterns. We don\'t pretend they\'re human — and that\'s fine, because the hook is what sells, not the face.' },
      { q: 'Will these pass Meta and TikTok ad approval?', a: 'Yes. Every video runs through a compliance review against current Meta, TikTok, and YouTube policy before delivery. We re-shoot anything that won\'t pass.' },
      { q: 'How is this different from a Canva-style AI tool?', a: 'You\'re not buying software — you\'re buying a video team. Scripting, generation, human editing, compliance, and weekly performance review are all included.' },
      { q: 'Can you match our existing brand voice?', a: 'Yes. We start with a brand & voice intake, build a custom avatar bank, and lock the tonal guardrails before the first video ships.' },
      { q: 'What if a hook flops?', a: 'It gets retired. We over-produce on purpose — 50 hooks/week is the volume that lets us cut fast and double down on what actually buys.' },
    ],
  },
}
