export const PROP_FIRMS = [
  {
    id: 'apex-edge',
    slug: 'apex-edge',
    name: 'Apex Edge Capital',
    domain: 'apexedge.example',
    initials: 'AE',
    rank: 1,
    editorPick: true,
    tagline: 'Two-step evaluation with instant funding on pass and a flat 90% split — the volume leader for futures traders in 2026.',
    rating: 4.8,
    reviews: 1283,
    tags: ['Futures', 'Forex', '90% split', 'Instant payouts'],
    stats: { funding: '$400K', split: '90 / 10', fee: 'from $97', payout: '24 hrs' },
    promo: { text: 'Save 25% on every evaluation account this month', code: 'CONTEGO25' },
  },
  {
    id: 'pinnacle-prop',
    slug: 'pinnacle-prop',
    name: 'Pinnacle Prop Trading',
    domain: 'pinnacleprop.example',
    initials: 'PP',
    rank: 2,
    tagline: 'One-step model with a generous 8% drawdown buffer. Strong scaling plan and no consistency rule on profitable days.',
    rating: 4.7,
    reviews: 942,
    tags: ['Forex', 'Crypto', 'One-step', 'No consistency rule'],
    stats: { funding: '$300K', split: 'up to 95%', fee: 'from $129', payout: '48 hrs' },
    promo: { text: 'Buy one, get a free reset on any failed account', code: 'CONTEGOFREE' },
  },
  {
    id: 'vertex-funded',
    slug: 'vertex-funded',
    name: 'Vertex Funded',
    domain: 'vertexfunded.example',
    initials: 'VF',
    rank: 3,
    tagline: 'Built for futures day-traders. Same-day payouts, weekly payout cycle, and one of the cheapest evaluations on the market.',
    rating: 4.6,
    reviews: 1547,
    tags: ['Futures', 'Daily payouts', 'Low fee'],
    stats: { funding: '$250K', split: '90 / 10', fee: 'from $49', payout: 'Same day' },
    promo: null,
  },
  {
    id: 'arc-trader',
    slug: 'arc-trader',
    name: 'Arc Trader',
    domain: 'arctrader.example',
    initials: 'AT',
    rank: 4,
    tagline: 'Instant-funding model with no evaluation step. Pay-once, trade live capital from day one — popular with experienced traders.',
    rating: 4.5,
    reviews: 612,
    tags: ['Instant funding', 'Forex', 'Indices'],
    stats: { funding: '$200K', split: '80 / 20', fee: 'from $299', payout: '72 hrs' },
    promo: null,
  },
  {
    id: 'meridian-capital',
    slug: 'meridian-capital',
    name: 'Meridian Capital Group',
    domain: 'meridiancap.example',
    initials: 'MC',
    rank: 5,
    tagline: 'Established 2019 — a more traditional two-step evaluation with a strong regulatory backbone and predictable payout schedule.',
    rating: 4.4,
    reviews: 2104,
    tags: ['Forex', 'Indices', 'Stocks', 'Established'],
    stats: { funding: '$500K', split: '85 / 15', fee: 'from $189', payout: 'Bi-weekly' },
    promo: null,
  },
  {
    id: 'helios-funded',
    slug: 'helios-funded',
    name: 'Helios Funded',
    domain: 'heliosfunded.example',
    initials: 'HF',
    rank: 6,
    tagline: 'Crypto-first prop firm with 24/7 trading windows, a $5M scaling cap, and the only crypto-native dashboard on this list.',
    rating: 4.4,
    reviews: 487,
    tags: ['Crypto', '24/7', 'Scaling to $5M'],
    stats: { funding: '$200K', split: '90 / 10', fee: 'from $99', payout: '24 hrs' },
    promo: { text: 'First profit split paid in stablecoins — zero fees', code: 'AUTOAPPLY' },
  },
  {
    id: 'northfield-trading',
    slug: 'northfield-trading',
    name: 'Northfield Trading',
    domain: 'northfield.example',
    initials: 'NT',
    rank: 7,
    tagline: 'Conservative risk model with a deep simulator and education tier. The best fit for newer traders who want guardrails in place.',
    rating: 4.3,
    reviews: 836,
    tags: ['Forex', 'Indices', 'Beginner-friendly'],
    stats: { funding: '$150K', split: '80 / 20', fee: 'from $89', payout: 'Bi-weekly' },
    promo: null,
  },
  {
    id: 'orbit-prop',
    slug: 'orbit-prop',
    name: 'Orbit Prop',
    domain: 'orbitprop.example',
    initials: 'OP',
    rank: 8,
    tagline: 'Aggressive scaling — double your account every 30 days on a 10% profit target. Pro-trader tier scales to $1.5M.',
    rating: 4.2,
    reviews: 391,
    tags: ['Forex', 'Futures', 'Aggressive scaling'],
    stats: { funding: '$300K', split: '85 / 15', fee: 'from $169', payout: '48 hrs' },
    promo: null,
  },
  {
    id: 'lumen-capital',
    slug: 'lumen-capital',
    name: 'Lumen Capital',
    domain: 'lumencap.example',
    initials: 'LC',
    rank: 9,
    tagline: 'A no-frills two-step program for swing traders. EA-friendly, weekend holding allowed, and no minimum trading-day rule.',
    rating: 4.2,
    reviews: 558,
    tags: ['Forex', 'EA-friendly', 'Swing-trading'],
    stats: { funding: '$200K', split: '80 / 20', fee: 'from $119', payout: 'Bi-weekly' },
    promo: null,
  },
  {
    id: 'quantum-fx',
    slug: 'quantum-fx',
    name: 'Quantum FX',
    domain: 'quantumfx.example',
    initials: 'QF',
    rank: 10,
    tagline: "A scalper's firm — 0.0 pip raw spread, tight execution, and a one-phase challenge with no time limit on the evaluation.",
    rating: 4.1,
    reviews: 274,
    tags: ['Forex', 'Scalping', 'Raw spread'],
    stats: { funding: '$100K', split: '80 / 20', fee: 'from $69', payout: '72 hrs' },
    promo: null,
  },
  {
    id: 'cascade-trading',
    slug: 'cascade-trading',
    name: 'Cascade Trading',
    domain: 'cascadetrading.example',
    initials: 'CT',
    rank: 11,
    tagline: 'Sleek two-step program with a friendly drawdown structure and 90% split — a solid middle-of-the-pack pick for forex day traders.',
    rating: 4.1,
    reviews: 419,
    tags: ['Forex', 'Indices', 'Two-step'],
    stats: { funding: '$200K', split: '90 / 10', fee: 'from $109', payout: '48 hrs' },
    promo: null,
  },
  {
    id: 'ironclad-capital',
    slug: 'ironclad-capital',
    name: 'Ironclad Capital',
    domain: 'ironclad.example',
    initials: 'IC',
    rank: 12,
    tagline: 'Conservative one-step model with a strict daily-loss rule. Best for traders who want predictability over aggressive scaling.',
    rating: 4.0,
    reviews: 312,
    tags: ['Forex', 'Indices', 'One-step'],
    stats: { funding: '$150K', split: '85 / 15', fee: 'from $99', payout: 'Weekly' },
    promo: null,
  },
  {
    id: 'beacon-funded',
    slug: 'beacon-funded',
    name: 'Beacon Funded',
    domain: 'beaconfunded.example',
    initials: 'BF',
    rank: 13,
    tagline: 'A futures-only firm with deep micro-contract support and Sunday trading windows — built for the dedicated CME crowd.',
    rating: 4.0,
    reviews: 226,
    tags: ['Futures', 'Micros', 'Weekend trading'],
    stats: { funding: '$150K', split: '90 / 10', fee: 'from $79', payout: '48 hrs' },
    promo: null,
  },
  {
    id: 'monolith-prop',
    slug: 'monolith-prop',
    name: 'Monolith Prop',
    domain: 'monolithprop.example',
    initials: 'MP',
    rank: 14,
    tagline: 'Two-step evaluation with a generous 10% profit target. Reliable monthly payouts and a clean trader dashboard.',
    rating: 3.9,
    reviews: 188,
    tags: ['Forex', 'Crypto', 'Monthly payouts'],
    stats: { funding: '$100K', split: '80 / 20', fee: 'from $89', payout: 'Monthly' },
    promo: null,
  },
  {
    id: 'horizon-fx',
    slug: 'horizon-fx',
    name: 'Horizon FX',
    domain: 'horizonfx.example',
    initials: 'HX',
    rank: 15,
    tagline: 'Newer entrant — competitive eval pricing, a clean rule set, and a working API for traders running their own automation stack.',
    rating: 3.9,
    reviews: 142,
    tags: ['Forex', 'API access', 'Automation'],
    stats: { funding: '$100K', split: '80 / 20', fee: 'from $59', payout: 'Bi-weekly' },
    promo: null,
  },
]

export const CATEGORIES = [
  { id: 'all', label: 'All firms' },
  { id: 'Forex', label: 'Forex' },
  { id: 'Futures', label: 'Futures' },
  { id: 'Crypto', label: 'Crypto' },
  { id: 'Indices', label: 'Indices' },
  { id: 'Stocks', label: 'Stocks' },
]

export const SORT_OPTIONS = [
  { id: 'rank', label: 'Editorial ranking' },
  { id: 'rating', label: 'Highest rated' },
  { id: 'reviews', label: 'Most reviewed' },
  { id: 'funding', label: 'Highest funding' },
]
